apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "white-ops.fullname" . }}-server
  labels:
    {{- include "white-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "white-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "white-ops.fullname" . }}-worker
  labels:
    {{- include "white-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "white-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "white-ops.fullname" . }}-web
  labels:
    {{- include "white-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "white-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
---
{{- if .Values.postgres.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "white-ops.fullname" . }}-postgres
  labels:
    {{- include "white-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "white-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgres
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "white-ops.fullname" . }}-redis
  labels:
    {{- include "white-ops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "white-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
{{- end }}
